# Generated by Django 3.2.3 on 2021-06-10 14:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('city', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CityHistoryModel',
        ),
        migrations.DeleteModel(
            name='CityModel',
        ),
    ]
