# Generated by Django 3.2.3 on 2021-06-10 14:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user_profile', '0004_auto_20210610_1014'),
        ('city', '0002_auto_20210610_2130'),
    ]

    operations = [
        migrations.CreateModel(
            name='CityModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=200)),
                ('street', models.CharField(max_length=200)),
                ('quote', models.TextField()),
                ('image', models.ImageField(upload_to='media/city')),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('updated_time', models.DateTimeField(auto_now=True)),
                ('profile_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='c_pf', to='user_profile.profilemodel')),
            ],
        ),
        migrations.CreateModel(
            name='HistoryModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=200, null=True)),
                ('street', models.CharField(max_length=200, null=True)),
                ('quote', models.TextField(null=True)),
                ('image', models.ImageField(null=True, upload_to='media/city')),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('city_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='city.citymodel')),
            ],
        ),
    ]
