# Generated by Django 3.2.3 on 2021-06-12 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('city', '0003_citymodel_historymodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='citymodel',
            name='bg_color',
            field=models.CharField(choices=[('', '')], default='', max_length=10),
        ),
    ]
