# Generated by Django 3.2.3 on 2021-06-12 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('city', '0004_citymodel_bg_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='historymodel',
            name='bg_color',
            field=models.CharField(default='', max_length=10),
        ),
    ]
