# Generated by Django 3.2.3 on 2021-07-26 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('city', '0005_historymodel_bg_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='citymodel',
            name='bg_color',
            field=models.IntegerField(choices=[(0, 'bg-primary.text-primary')], default=0),
        ),
    ]
