# Generated by Django 3.2.3 on 2021-05-18 10:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user_profile', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RefreshTokenModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('refresh_token', models.CharField(max_length=300)),
                ('updated_time', models.DateTimeField(auto_now=True)),
                ('profile_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pf_rf_t', to='user_profile.profilemodel')),
            ],
        ),
    ]
