# Generated by Django 3.2.3 on 2021-05-18 14:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0001_initial'),
        ('facebook', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='likemodel',
            name='profile_model',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pf_like', to='user_profile.profilemodel'),
        ),
        migrations.AddField(
            model_name='sharemodel',
            name='profile_model',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pf_share', to='user_profile.profilemodel'),
        ),
        migrations.AlterField(
            model_name='postmodel',
            name='post_to_where',
            field=models.CharField(choices=[('0', 'group'), ('1', 'user')], max_length=100),
        ),
    ]
