# Generated by Django 3.2.3 on 2021-05-18 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facebook', '0002_auto_20210518_2121'),
    ]

    operations = [
        migrations.AddField(
            model_name='postmodel',
            name='created_time',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='postmodel',
            name='updated_time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
