# Generated by Django 3.2.3 on 2021-06-09 14:26

import _common.models.valid_field
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user_profile', '0002_auto_20210609_2126'),
        ('facebook', '0006_auto_20210607_1445'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommentModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(null=True)),
                ('vid_pic', models.FileField(null=True, upload_to='', validators=[_common.models.valid_field.valid_vid_pic])),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('updated_time', models.DateTimeField(auto_now=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='HistoryModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(default='', null=True)),
                ('created_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='PostModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('share_post_model', models.IntegerField(null=True)),
                ('post_to_where', models.CharField(choices=[('0', 'group'), ('1', 'user')], max_length=100)),
                ('post_to_id', models.IntegerField()),
                ('content', models.TextField(default='', null=True)),
                ('created_time', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_time', models.DateTimeField(auto_now=True)),
                ('profile_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pf_post', to='user_profile.profilemodel')),
            ],
        ),
        migrations.CreateModel(
            name='VidPicCmtModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(null=True)),
                ('vid_pic', models.FileField(null=True, upload_to='', validators=[_common.models.valid_field.valid_vid_pic])),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('updated_time', models.DateTimeField(auto_now=True)),
                ('profile_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pf_vp_cmt', to='user_profile.profilemodel')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='VidPicModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(default='', null=True)),
                ('vid_pic', models.FileField(null=True, upload_to='', validators=[_common.models.valid_field.valid_vid_pic])),
                ('post_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='p_v_p', to='facebook.postmodel')),
            ],
        ),
        migrations.CreateModel(
            name='VidPicSubModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(null=True)),
                ('vid_pic', models.FileField(null=True, upload_to='', validators=[_common.models.valid_field.valid_vid_pic])),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('updated_time', models.DateTimeField(auto_now=True)),
                ('profile_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pf_vp_sub', to='user_profile.profilemodel')),
                ('vid_pic_comment_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cmt_sub', to='facebook.vidpiccmtmodel')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='VidPicSubLikeModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_like', models.IntegerField(choices=[(0, 'like'), (1, 'heart'), (2, 'laugh'), (3, 'sad'), (4, 'wow'), (5, 'angry')])),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('profile_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pf_vp_sub_like', to='user_profile.profilemodel')),
                ('vid_pic_sub_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sub_like', to='facebook.vidpicsubmodel')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='VidPicSubHistoryModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(null=True)),
                ('vid_pic', models.TextField(null=True)),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('profile_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pf_vp_sub_his', to='user_profile.profilemodel')),
                ('vid_pic_sub_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sub_his', to='facebook.vidpicsubmodel')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='VidPicShareModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField()),
                ('profile_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pf_vp_sh', to='user_profile.profilemodel')),
                ('vid_pic_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vp_share', to='facebook.vidpicmodel')),
            ],
        ),
        migrations.CreateModel(
            name='VidPicLikeModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_like', models.IntegerField(choices=[(0, 'like'), (1, 'heart'), (2, 'laugh'), (3, 'sad'), (4, 'wow'), (5, 'angry')])),
                ('profile_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pf_vp_l', to='user_profile.profilemodel')),
                ('vid_pic_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vp_like', to='facebook.vidpicmodel')),
            ],
        ),
        migrations.CreateModel(
            name='VidPicHistoryModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('vid_pic_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vp_his', to='facebook.vidpicmodel')),
            ],
        ),
        migrations.AddField(
            model_name='vidpiccmtmodel',
            name='vid_pic_model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vp_vp_vmt', to='facebook.vidpicmodel'),
        ),
        migrations.CreateModel(
            name='VidPicCmtLikeModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_like', models.IntegerField(choices=[(0, 'like'), (1, 'heart'), (2, 'laugh'), (3, 'sad'), (4, 'wow'), (5, 'angry')])),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('profile_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pf_vp_cmt_l', to='user_profile.profilemodel')),
                ('vid_pic_Cmt_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vp_cmt_like', to='facebook.vidpiccmtmodel')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='VidPicCmtHistoryModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(null=True)),
                ('vid_pic', models.TextField(null=True)),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('vid_pic_Cmt_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vp_cmt_his', to='facebook.vidpiccmtmodel')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SubModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(null=True)),
                ('vid_pic', models.FileField(null=True, upload_to='', validators=[_common.models.valid_field.valid_vid_pic])),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('updated_time', models.DateTimeField(auto_now=True)),
                ('comment_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cmt_sub', to='facebook.commentmodel')),
                ('profile_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pf_sub', to='user_profile.profilemodel')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SubLikeModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_like', models.IntegerField(choices=[(0, 'like'), (1, 'heart'), (2, 'laugh'), (3, 'sad'), (4, 'wow'), (5, 'angry')])),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('profile_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pf_sub_l', to='user_profile.profilemodel')),
                ('sub_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sub_like', to='facebook.submodel')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SubHistoryModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(null=True)),
                ('vid_pic', models.TextField(null=True)),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('sub_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sub_his', to='facebook.submodel')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ShareModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField()),
                ('post_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='p_share', to='facebook.postmodel')),
                ('profile_model', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pf_share', to='user_profile.profilemodel')),
            ],
        ),
        migrations.CreateModel(
            name='LikeModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_like', models.IntegerField(choices=[(0, 'like'), (1, 'heart'), (2, 'laugh'), (3, 'sad'), (4, 'wow'), (5, 'angry')])),
                ('post_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='p_like', to='facebook.postmodel')),
                ('profile_model', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pf_like', to='user_profile.profilemodel')),
            ],
        ),
        migrations.CreateModel(
            name='HistoryVidPicDelModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vid_pic', models.TextField()),
                ('his_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='h_h_v_p_d', to='facebook.historymodel')),
            ],
        ),
        migrations.CreateModel(
            name='HistoryVidPicCreateModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vid_pic', models.TextField()),
                ('his_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='h_h_v_p_c', to='facebook.historymodel')),
            ],
        ),
        migrations.AddField(
            model_name='historymodel',
            name='post_model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='p_his', to='facebook.postmodel'),
        ),
        migrations.AddField(
            model_name='commentmodel',
            name='post_model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='p_cmt', to='facebook.postmodel'),
        ),
        migrations.AddField(
            model_name='commentmodel',
            name='profile_model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pf_cmt', to='user_profile.profilemodel'),
        ),
        migrations.CreateModel(
            name='CmtLikeModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_like', models.IntegerField(choices=[(0, 'like'), (1, 'heart'), (2, 'laugh'), (3, 'sad'), (4, 'wow'), (5, 'angry')])),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('comment_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cmt_cmt_like', to='facebook.commentmodel')),
                ('profile_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pf_cmt_l', to='user_profile.profilemodel')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CmtHistoryModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(null=True)),
                ('vid_pic', models.TextField(null=True)),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('comment_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cmt_cmt_his', to='facebook.commentmodel')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
