# Generated by Django 3.2.3 on 2021-06-13 02:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('facebook', '0007_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vidpiccmthistorymodel',
            old_name='vid_pic_Cmt_model',
            new_name='comment_model',
        ),
        migrations.RenameField(
            model_name='vidpiccmtlikemodel',
            old_name='vid_pic_Cmt_model',
            new_name='comment_model',
        ),
        migrations.RenameField(
            model_name='vidpicsubhistorymodel',
            old_name='vid_pic_sub_model',
            new_name='sub_model',
        ),
        migrations.RenameField(
            model_name='vidpicsublikemodel',
            old_name='vid_pic_sub_model',
            new_name='sub_model',
        ),
        migrations.RenameField(
            model_name='vidpicsubmodel',
            old_name='vid_pic_comment_model',
            new_name='comment_model',
        ),
        migrations.RemoveField(
            model_name='postmodel',
            name='share_post_model',
        ),
        migrations.AddField(
            model_name='postmodel',
            name='permission',
            field=models.IntegerField(choices=[(0, 'public'), (1, 'mutual_friend'), (2, 'friend'), (3, 'private')], default=0),
        ),
        migrations.AddField(
            model_name='postmodel',
            name='type_post',
            field=models.CharField(choices=[('POST', 'post'), ('SHARE', 'share'), ('PICTURE', 'picture'), ('COVER', 'cover')], default='post', max_length=50),
        ),
        migrations.AlterField(
            model_name='postmodel',
            name='post_to_where',
            field=models.CharField(choices=[('GROUP', 'group'), ('USER', 'user')], max_length=100),
        ),
        migrations.CreateModel(
            name='PostShareModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_model', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='p_p_sh', to='facebook.postmodel')),
                ('post_share_model', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='p_sh_p_sh', to='facebook.postmodel')),
            ],
        ),
    ]
