# Generated by Django 3.2.3 on 2021-07-22 13:59

import _common.models.valid_field
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facebook', '0009_auto_20210615_1418'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commentmodel',
            name='vid_pic',
            field=models.FileField(null=True, upload_to='media/facebook/post', validators=[_common.models.valid_field.valid_vid_pic]),
        ),
        migrations.AlterField(
            model_name='submodel',
            name='vid_pic',
            field=models.FileField(null=True, upload_to='media/facebook/post', validators=[_common.models.valid_field.valid_vid_pic]),
        ),
        migrations.AlterField(
            model_name='vidpiccmtmodel',
            name='vid_pic',
            field=models.FileField(null=True, upload_to='media/facebook/post', validators=[_common.models.valid_field.valid_vid_pic]),
        ),
        migrations.AlterField(
            model_name='vidpicsubmodel',
            name='vid_pic',
            field=models.FileField(null=True, upload_to='media/facebook/post', validators=[_common.models.valid_field.valid_vid_pic]),
        ),
    ]
