# Generated by Django 3.2.3 on 2021-07-22 13:59

import _common.models.valid_field
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user_profile', '0006_personalsettingmodel_permission_see_interactive'),
    ]

    operations = [
        migrations.CreateModel(
            name='MessageModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('created_time', models.DateTimeField(auto_now=True)),
                ('profile_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_profile.profilemodel')),
            ],
        ),
        migrations.CreateModel(
            name='RoomModel',
            fields=[
                ('room_chat', models.CharField(max_length=100, primary_key=True, serialize=False, unique=True)),
                ('is_group', models.BooleanField()),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('updated_time', models.DateTimeField(auto_now=True)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='r_cr', to='user_profile.profilemodel')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='r_o', to='user_profile.profilemodel')),
            ],
        ),
        migrations.CreateModel(
            name='VidPicModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vid_pic', models.FileField(upload_to='', validators=[_common.models.valid_field.valid_vid_pic])),
                ('mess_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chat.messagemodel')),
            ],
        ),
        migrations.CreateModel(
            name='TimelineModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=100)),
                ('created_time', models.DateTimeField(auto_now=True)),
                ('friend_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nt_fr', to='user_profile.profilemodel')),
                ('profile_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nt_pf', to='user_profile.profilemodel')),
                ('room_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chat.roommodel')),
            ],
        ),
        migrations.CreateModel(
            name='RoomUserModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_notice', models.BooleanField(default=True)),
                ('on_chat', models.BooleanField(default=False)),
                ('on_input', models.BooleanField(default=False)),
                ('begin_mess', models.IntegerField(default=0)),
                ('last_seen', models.IntegerField(default=0)),
                ('last_receive', models.IntegerField(default=0)),
                ('joined_time', models.DateTimeField(auto_now_add=True)),
                ('profile_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_profile.profilemodel')),
                ('room_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chat.roommodel')),
            ],
        ),
        migrations.AddField(
            model_name='messagemodel',
            name='room_model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chat.roommodel'),
        ),
        migrations.CreateModel(
            name='LikeModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_like', models.IntegerField(choices=[(0, 'like'), (1, 'heart'), (2, 'laugh'), (3, 'sad'), (4, 'wow'), (5, 'angry')])),
                ('created_time', models.DateTimeField(auto_now=True)),
                ('mess_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chat.messagemodel')),
                ('profile_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_profile.profilemodel')),
            ],
        ),
    ]
