# Generated by Django 3.2.3 on 2021-07-23 07:56

import _common.models.valid_field
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0006_personalsettingmodel_permission_see_interactive'),
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='roomusermodel',
            name='last_mess',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='timelinemodel',
            name='friend_model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tl_fr', to='user_profile.profilemodel'),
        ),
        migrations.AlterField(
            model_name='timelinemodel',
            name='profile_model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tl_pf', to='user_profile.profilemodel'),
        ),
        migrations.AlterField(
            model_name='vidpicmodel',
            name='vid_pic',
            field=models.FileField(upload_to='media/chat', validators=[_common.models.valid_field.valid_vid_pic]),
        ),
    ]
