# Generated by Django 3.2.3 on 2021-06-09 14:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user_profile', '0002_auto_20210609_2126'),
    ]

    operations = [
        migrations.CreateModel(
            name='FriendModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_time', models.DateField(auto_now_add=True)),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fr_rc', to='user_profile.profilemodel')),
                ('requester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fr_rq', to='user_profile.profilemodel')),
            ],
        ),
        migrations.CreateModel(
            name='AddFriendModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_time', models.DateField(auto_now_add=True)),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='a_fr_rc', to='user_profile.profilemodel')),
                ('requester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='a_fr_rq', to='user_profile.profilemodel')),
            ],
        ),
    ]
