# Generated by Django 3.2.3 on 2021-07-23 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notice', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='noticemodel',
            name='link_id',
            field=models.CharField(max_length=200),
        ),
    ]
