# Generated by Django 3.2.3 on 2021-05-19 08:26

import _common.models.valid_field
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user_profile', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ProductCmtModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('created_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProductModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=200)),
                ('type', models.CharField(max_length=200)),
                ('hashtag', models.CharField(max_length=300)),
                ('name', models.CharField(max_length=200)),
                ('new_price', models.IntegerField()),
                ('old_price', models.IntegerField()),
                ('discount', models.IntegerField()),
                ('description', models.TextField()),
                ('total', models.IntegerField()),
                ('sold', models.IntegerField()),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('updated_time', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ShopModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('picture', models.ImageField(upload_to='')),
                ('banner', models.ImageField(upload_to='')),
                ('address', models.CharField(max_length=400)),
                ('info', models.TextField()),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('updated_time', models.DateTimeField(auto_now=True)),
                ('profile_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pf_sh', to='user_profile.profilemodel')),
            ],
        ),
        migrations.CreateModel(
            name='TransportModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('info', models.TextField()),
                ('created_time', models.DateTimeField(auto_now=True)),
                ('updated_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='TransportPriceModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('info', models.TextField()),
                ('price', models.IntegerField()),
                ('created_time', models.DateTimeField(auto_now=True)),
                ('updated_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='VoucherModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('condition_price', models.IntegerField()),
                ('cost', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='VoucherPaymentModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pm_vc_pm', to='shopee.paymentmodel')),
                ('voucher_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vc_vc_pm', to='shopee.vouchermodel')),
            ],
        ),
        migrations.CreateModel(
            name='ShopVoucherPriceModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('percent', models.IntegerField()),
                ('min_price', models.IntegerField()),
                ('shop_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sh_vc_pr', to='shopee.shopmodel')),
            ],
        ),
        migrations.CreateModel(
            name='ShopVoucherAmountModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('percent', models.IntegerField()),
                ('min_amount', models.IntegerField()),
                ('shop_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sh_vc_am', to='shopee.shopmodel')),
            ],
        ),
        migrations.CreateModel(
            name='ShopVidPicModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vid_pic', models.FileField(upload_to='', validators=[_common.models.valid_field.valid_vid_pic])),
                ('shop_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sh_vp', to='shopee.shopmodel')),
            ],
        ),
        migrations.CreateModel(
            name='ShopGroupModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_name', models.CharField(max_length=300)),
                ('shop_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sh_gr', to='shopee.shopmodel')),
            ],
        ),
        migrations.CreateModel(
            name='ShopGiftModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='')),
                ('shop_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sh_gift', to='shopee.shopmodel')),
            ],
        ),
        migrations.CreateModel(
            name='ProductVidPicModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vid_pic', models.FileField(upload_to='', validators=[_common.models.valid_field.valid_vid_pic])),
                ('product_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pd_vp', to='shopee.productmodel')),
            ],
        ),
        migrations.CreateModel(
            name='ProductRateModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('num_rate', models.IntegerField()),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('product_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pd_rate', to='shopee.productmodel')),
                ('profile_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pf_rate', to='user_profile.profilemodel')),
            ],
        ),
        migrations.AddField(
            model_name='productmodel',
            name='group_model',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='gr_pd', to='shopee.shopgroupmodel'),
        ),
        migrations.AddField(
            model_name='productmodel',
            name='shop_model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sh_pd', to='shopee.shopmodel'),
        ),
        migrations.CreateModel(
            name='ProductCmtVidPicModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vid_pic', models.FileField(upload_to='', validators=[_common.models.valid_field.valid_vid_pic])),
                ('comment_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pd_vp', to='shopee.productcmtmodel')),
            ],
        ),
        migrations.AddField(
            model_name='productcmtmodel',
            name='product_model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pd_cmt', to='shopee.productmodel'),
        ),
        migrations.AddField(
            model_name='productcmtmodel',
            name='profile_model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pf_cmt', to='user_profile.profilemodel'),
        ),
        migrations.CreateModel(
            name='CartModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('product_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pd_cart', to='shopee.productmodel')),
                ('profile_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pf_cart', to='user_profile.profilemodel')),
            ],
        ),
        migrations.CreateModel(
            name='CancelModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('product_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pd_cc', to='shopee.productmodel')),
                ('profile_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pf_cc', to='user_profile.profilemodel')),
            ],
        ),
        migrations.CreateModel(
            name='BuyModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transport_name', models.CharField(max_length=400)),
                ('trans_price', models.IntegerField()),
                ('quantity', models.IntegerField()),
                ('status', models.CharField(max_length=100)),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('product_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pd_buy', to='shopee.productmodel')),
                ('profile_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pf_buy', to='user_profile.profilemodel')),
            ],
        ),
    ]
