# Generated by Django 3.2.3 on 2021-06-11 09:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shopee', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartmodel',
            name='checked',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='productmodel',
            name='rate',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='transportpricemodel',
            name='transport_model',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='shopee.transportmodel'),
        ),
        migrations.AlterField(
            model_name='productcmtmodel',
            name='content',
            field=models.TextField(null=True),
        ),
    ]
