# Generated by Django 3.2.3 on 2021-06-11 09:45

import _common.models.valid_field
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shopee', '0002_auto_20210611_1614'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productvidpicmodel',
            name='vid_pic',
            field=models.FileField(upload_to='media/shopee/product', validators=[_common.models.valid_field.valid_vid_pic]),
        ),
        migrations.AlterField(
            model_name='shopvidpicmodel',
            name='vid_pic',
            field=models.FileField(upload_to='media/shopee', validators=[_common.models.valid_field.valid_vid_pic]),
        ),
        migrations.AlterField(
            model_name='voucherpaymentmodel',
            name='payment_model',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pm_vc_pm', to='shopee.paymentmodel'),
        ),
    ]
