# Generated by Django 3.2.3 on 2021-06-12 05:18

import _common.models.valid_field
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0004_auto_20210610_1014'),
        ('shopee', '0003_auto_20210611_1645'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productcmtmodel',
            name='product_model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shopee.productmodel'),
        ),
        migrations.AlterField(
            model_name='productcmtmodel',
            name='profile_model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_profile.profilemodel'),
        ),
        migrations.AlterField(
            model_name='productcmtvidpicmodel',
            name='comment_model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shopee.productcmtmodel'),
        ),
        migrations.AlterField(
            model_name='productcmtvidpicmodel',
            name='vid_pic',
            field=models.FileField(upload_to='media/shopee/product/cmt', validators=[_common.models.valid_field.valid_vid_pic]),
        ),
        migrations.AlterField(
            model_name='shopmodel',
            name='banner',
            field=models.ImageField(upload_to='media/shopee'),
        ),
        migrations.AlterField(
            model_name='shopmodel',
            name='picture',
            field=models.ImageField(upload_to='media/shopee'),
        ),
    ]
