# Generated by Django 3.2.3 on 2021-05-18 10:38

import _common.models.valid_field
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProfileModel',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('picture', models.CharField(max_length=300, null=True)),
                ('cover', models.CharField(max_length=300, null=True)),
                ('picture_id', models.IntegerField(null=True)),
                ('cover_id', models.IntegerField(null=True)),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('name_updated_time', models.DateTimeField()),
                ('nick_name', models.CharField(max_length=50, null=True)),
                ('hobby', models.TextField(null=True)),
                ('story', models.TextField(null=True)),
                ('birth', models.DateTimeField(null=True)),
                ('email', models.EmailField(max_length=254, null=True)),
                ('phone', models.IntegerField(null=True, validators=[_common.models.valid_field.valid_number_phone])),
                ('address', models.CharField(max_length=200, null=True)),
                ('permission_birth', models.IntegerField(choices=[(0, 'public'), (1, 'mutual_friend'), (2, 'friend'), (3, 'private')], default=0)),
                ('permission_phone', models.IntegerField(choices=[(0, 'public'), (1, 'mutual_friend'), (2, 'friend'), (3, 'private')], default=0)),
                ('permission_friends', models.IntegerField(choices=[(0, 'public'), (1, 'mutual_friend'), (2, 'friend'), (3, 'private')], default=0)),
                ('permission_email', models.IntegerField(choices=[(0, 'public'), (1, 'mutual_friend'), (2, 'friend'), (3, 'private')], default=0)),
                ('permission_address', models.IntegerField(choices=[(0, 'public'), (1, 'mutual_friend'), (2, 'friend'), (3, 'private')], default=0)),
                ('work', models.CharField(max_length=200, null=True)),
                ('university', models.CharField(max_length=100, null=True)),
                ('high_school', models.CharField(max_length=100, null=True)),
                ('is_online', models.BooleanField(default=False)),
                ('created_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
