# Generated by Django 3.2.3 on 2021-06-09 14:26

import _common.models.valid_field
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profilemodel',
            name='address',
        ),
        migrations.RemoveField(
            model_name='profilemodel',
            name='birth',
        ),
        migrations.RemoveField(
            model_name='profilemodel',
            name='cover',
        ),
        migrations.RemoveField(
            model_name='profilemodel',
            name='cover_id',
        ),
        migrations.RemoveField(
            model_name='profilemodel',
            name='email',
        ),
        migrations.RemoveField(
            model_name='profilemodel',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='profilemodel',
            name='high_school',
        ),
        migrations.RemoveField(
            model_name='profilemodel',
            name='hobby',
        ),
        migrations.RemoveField(
            model_name='profilemodel',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='profilemodel',
            name='name_updated_time',
        ),
        migrations.RemoveField(
            model_name='profilemodel',
            name='nick_name',
        ),
        migrations.RemoveField(
            model_name='profilemodel',
            name='permission_address',
        ),
        migrations.RemoveField(
            model_name='profilemodel',
            name='permission_birth',
        ),
        migrations.RemoveField(
            model_name='profilemodel',
            name='permission_email',
        ),
        migrations.RemoveField(
            model_name='profilemodel',
            name='permission_friends',
        ),
        migrations.RemoveField(
            model_name='profilemodel',
            name='permission_phone',
        ),
        migrations.RemoveField(
            model_name='profilemodel',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='profilemodel',
            name='picture',
        ),
        migrations.RemoveField(
            model_name='profilemodel',
            name='picture_id',
        ),
        migrations.RemoveField(
            model_name='profilemodel',
            name='story',
        ),
        migrations.RemoveField(
            model_name='profilemodel',
            name='university',
        ),
        migrations.RemoveField(
            model_name='profilemodel',
            name='work',
        ),
        migrations.CreateModel(
            name='WorkModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('work', models.CharField(max_length=200)),
                ('permission', models.IntegerField(choices=[(0, 'public'), (1, 'mutual_friend'), (2, 'friend'), (3, 'private')], default=0)),
                ('profile_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_profile.profilemodel')),
            ],
        ),
        migrations.CreateModel(
            name='UniversityModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('university', models.CharField(max_length=200)),
                ('permission', models.IntegerField(choices=[(0, 'public'), (1, 'mutual_friend'), (2, 'friend'), (3, 'private')], default=0)),
                ('profile_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_profile.profilemodel')),
            ],
        ),
        migrations.CreateModel(
            name='TownModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('town', models.CharField(max_length=200)),
                ('permission', models.IntegerField(choices=[(0, 'public'), (1, 'mutual_friend'), (2, 'friend'), (3, 'private')], default=0)),
                ('profile_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_profile.profilemodel')),
            ],
        ),
        migrations.CreateModel(
            name='SchoolModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school', models.CharField(max_length=200)),
                ('permission', models.IntegerField(choices=[(0, 'public'), (1, 'mutual_friend'), (2, 'friend'), (3, 'private')], default=0)),
                ('profile_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_profile.profilemodel')),
            ],
        ),
        migrations.CreateModel(
            name='RelationModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relation', models.CharField(choices=[], max_length=100)),
                ('permission', models.IntegerField(choices=[(0, 'public'), (1, 'mutual_friend'), (2, 'friend'), (3, 'private')], default=0)),
                ('profile_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_profile.profilemodel')),
            ],
        ),
        migrations.CreateModel(
            name='PictureModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=300, null=True)),
                ('post_id', models.IntegerField(null=True)),
                ('permission', models.IntegerField(choices=[(0, 'public'), (1, 'mutual_friend'), (2, 'friend'), (3, 'private')], default=0)),
                ('is_active', models.BooleanField()),
                ('profile_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_profile.profilemodel')),
            ],
        ),
        migrations.CreateModel(
            name='PhoneModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.IntegerField(null=True, validators=[_common.models.valid_field.valid_number_phone])),
                ('permission', models.IntegerField(choices=[(0, 'public'), (1, 'mutual_friend'), (2, 'friend'), (3, 'private')], default=0)),
                ('profile_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_profile.profilemodel')),
            ],
        ),
        migrations.CreateModel(
            name='PersonalSettingModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('permission_see_friend', models.IntegerField()),
                ('permission_add_friend', models.IntegerField()),
                ('permission_follow', models.IntegerField()),
                ('permission_post', models.IntegerField()),
                ('profile_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_profile.profilemodel')),
            ],
        ),
        migrations.CreateModel(
            name='OtherNameModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('other_name', models.CharField(max_length=200)),
                ('permission', models.IntegerField(choices=[(0, 'public'), (1, 'mutual_friend'), (2, 'friend'), (3, 'private')], default=0)),
                ('profile_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_profile.profilemodel')),
            ],
        ),
        migrations.CreateModel(
            name='NameModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('updated_time', models.DateTimeField(auto_now=True)),
                ('profile_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_profile.profilemodel')),
            ],
        ),
        migrations.CreateModel(
            name='MailModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mail', models.EmailField(max_length=254)),
                ('permission', models.IntegerField(choices=[(0, 'public'), (1, 'mutual_friend'), (2, 'friend'), (3, 'private')], default=0)),
                ('profile_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_profile.profilemodel')),
            ],
        ),
        migrations.CreateModel(
            name='LifeEventModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('life_event', models.CharField(max_length=500)),
                ('permission', models.IntegerField(choices=[(0, 'public'), (1, 'mutual_friend'), (2, 'friend'), (3, 'private')], default=0)),
                ('profile_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_profile.profilemodel')),
            ],
        ),
        migrations.CreateModel(
            name='LanguageModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lang', models.CharField(max_length=50)),
                ('permission', models.IntegerField(choices=[(0, 'public'), (1, 'mutual_friend'), (2, 'friend'), (3, 'private')], default=0)),
                ('profile_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_profile.profilemodel')),
            ],
        ),
        migrations.CreateModel(
            name='HobbyModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hobby', models.TextField()),
                ('permission', models.IntegerField(choices=[(0, 'public'), (1, 'mutual_friend'), (2, 'friend'), (3, 'private')], default=0)),
                ('profile_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_profile.profilemodel')),
            ],
        ),
        migrations.CreateModel(
            name='GenderModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.CharField(choices=[], max_length=10)),
                ('permission', models.IntegerField(choices=[(0, 'public'), (1, 'mutual_friend'), (2, 'friend'), (3, 'private')], default=0)),
                ('profile_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_profile.profilemodel')),
            ],
        ),
        migrations.CreateModel(
            name='FamilyModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('permission', models.IntegerField(choices=[(0, 'public'), (1, 'mutual_friend'), (2, 'friend'), (3, 'private')], default=0)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='family_member', to='user_profile.profilemodel')),
                ('profile_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_profile.profilemodel')),
            ],
        ),
        migrations.CreateModel(
            name='CoverModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=300, null=True)),
                ('post_id', models.IntegerField(null=True)),
                ('permission', models.IntegerField(choices=[(0, 'public'), (1, 'mutual_friend'), (2, 'friend'), (3, 'private')], default=0)),
                ('is_active', models.BooleanField()),
                ('profile_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_profile.profilemodel')),
            ],
        ),
        migrations.CreateModel(
            name='CityModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=200)),
                ('permission', models.IntegerField(choices=[(0, 'public'), (1, 'mutual_friend'), (2, 'friend'), (3, 'private')], default=0)),
                ('profile_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_profile.profilemodel')),
            ],
        ),
        migrations.CreateModel(
            name='BirthModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('birth', models.DateField()),
                ('permission', models.IntegerField(choices=[(0, 'public'), (1, 'mutual_friend'), (2, 'friend'), (3, 'private')], default=0)),
                ('profile_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_profile.profilemodel')),
            ],
        ),
        migrations.CreateModel(
            name='AddressModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=200)),
                ('permission', models.IntegerField(choices=[(0, 'public'), (1, 'mutual_friend'), (2, 'friend'), (3, 'private')], default=0)),
                ('profile_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_profile.profilemodel')),
            ],
        ),
        migrations.CreateModel(
            name='AboutYouModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('you', models.TextField()),
                ('permission', models.IntegerField(choices=[(0, 'public'), (1, 'mutual_friend'), (2, 'friend'), (3, 'private')], default=0)),
                ('profile_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_profile.profilemodel')),
            ],
        ),
    ]
