# Generated by Django 3.2.3 on 2021-06-10 03:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0002_auto_20210609_2126'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='namemodel',
            name='id',
        ),
        migrations.AlterField(
            model_name='covermodel',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='namemodel',
            name='profile_model',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='user_profile.profilemodel'),
        ),
        migrations.AlterField(
            model_name='personalsettingmodel',
            name='permission_add_friend',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='personalsettingmodel',
            name='permission_follow',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='personalsettingmodel',
            name='permission_post',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='personalsettingmodel',
            name='permission_see_friend',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='picturemodel',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
