# Generated by Django 3.2.3 on 2021-06-10 03:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0003_auto_20210610_1007'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='personalsettingmodel',
            name='id',
        ),
        migrations.AlterField(
            model_name='personalsettingmodel',
            name='profile_model',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='user_profile.profilemodel'),
        ),
    ]
