# Generated by Django 3.2.3 on 2021-06-13 02:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('facebook', '0008_auto_20210613_0917'),
        ('user_profile', '0004_auto_20210610_1014'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='covermodel',
            name='permission',
        ),
        migrations.RemoveField(
            model_name='covermodel',
            name='post_id',
        ),
        migrations.RemoveField(
            model_name='picturemodel',
            name='permission',
        ),
        migrations.RemoveField(
            model_name='picturemodel',
            name='post_id',
        ),
        migrations.AddField(
            model_name='covermodel',
            name='post_model',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='p_cover', to='facebook.postmodel'),
        ),
        migrations.AddField(
            model_name='picturemodel',
            name='post_model',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='p_pic', to='facebook.postmodel'),
        ),
    ]
