# Generated by Django 3.2.3 on 2021-06-15 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0005_auto_20210613_0917'),
    ]

    operations = [
        migrations.AddField(
            model_name='personalsettingmodel',
            name='permission_see_interactive',
            field=models.IntegerField(default=0),
        ),
    ]
