# Generated by Django 3.2.3 on 2021-07-23 07:56

import _common.models.valid_field
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PhoneLapModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('in_stock', models.CharField(max_length=200)),
                ('discount', models.IntegerField()),
                ('installment', models.IntegerField()),
                ('gift', models.TextField()),
                ('product_sets', models.TextField()),
                ('promotion', models.TextField()),
                ('cpu', models.TextField()),
                ('os', models.CharField(max_length=50)),
                ('ram', models.CharField(max_length=200)),
                ('internal_memory', models.CharField(max_length=200)),
                ('camera', models.TextField()),
                ('memory_stick', models.CharField(max_length=200)),
                ('type_product', models.CharField(max_length=200)),
                ('name', models.CharField(max_length=200)),
                ('new_price', models.IntegerField()),
                ('old_price', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='VidPicModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vid_pic', models.FileField(upload_to='media/phone_lap', validators=[_common.models.valid_field.valid_vid_pic])),
                ('phone_lap_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='phone_lap.phonelapmodel')),
            ],
        ),
        migrations.CreateModel(
            name='TypeModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.FileField(upload_to='media/phone_lap', validators=[_common.models.valid_field.valid_vid_pic])),
                ('color', models.CharField(max_length=100)),
                ('title', models.TextField()),
                ('phone_lap_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='phone_lap.phonelapmodel')),
            ],
        ),
        migrations.CreateModel(
            name='OrderModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('address', models.CharField(max_length=200)),
                ('number_phone', models.CharField(max_length=11, validators=[_common.models.valid_field.valid_number_phone])),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('type_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='phone_lap.typemodel')),
            ],
        ),
    ]
