# Generated by Django 3.2.3 on 2021-07-23 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phone_lap', '0002_auto_20210723_1551'),
    ]

    operations = [
        migrations.AddField(
            model_name='phonelapmodel',
            name='cpu_lv',
            field=models.IntegerField(choices=[(0, '4 cores'), (1, '8 cores')], default=0),
        ),
        migrations.AddField(
            model_name='phonelapmodel',
            name='cpu_type',
            field=models.CharField(choices=[(0, 'Snapdragon'), (1, 'Helio'), (2, 'Quacom')], default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='phonelapmodel',
            name='camera_type',
            field=models.CharField(choices=[(0, 'In dark'), (1, 'Beautiful')], default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='phonelapmodel',
            name='internal_memory_lv',
            field=models.IntegerField(choices=[(0, '< 4G'), (1, '4-8G'), (2, '0-16G'), (2, '16-32G'), (2, '>= 32G')], default=0),
        ),
        migrations.AlterField(
            model_name='phonelapmodel',
            name='memory_stick_lv',
            field=models.IntegerField(choices=[(0, ''), (1, ''), (2, '')], default=0),
        ),
        migrations.AlterField(
            model_name='phonelapmodel',
            name='ram_lv',
            field=models.IntegerField(choices=[(0, '< 2G'), (1, '2-4G'), (2, '4-6G'), (3, '>= 6G')], default=0),
        ),
    ]
