# Generated by Django 3.2.3 on 2021-07-23 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phone_lap', '0003_auto_20210723_1615'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phonelapmodel',
            name='camera_type',
            field=models.IntegerField(choices=[(0, 'In dark'), (1, 'Beautiful')], default=0),
        ),
        migrations.AlterField(
            model_name='phonelapmodel',
            name='cpu_type',
            field=models.IntegerField(choices=[(0, 'Snapdragon'), (1, 'Helio'), (2, 'Quacom')], default=0),
        ),
        migrations.AlterField(
            model_name='phonelapmodel',
            name='in_stock',
            field=models.IntegerField(choices=[(0, 'In stock'), (1, 'Out of stock'), (2, 'Incoming stock')]),
        ),
        migrations.AlterField(
            model_name='phonelapmodel',
            name='internal_memory_lv',
            field=models.IntegerField(choices=[(0, '< 4G'), (1, '4-8G'), (2, '0-16G'), (3, '16-32G'), (4, '>= 32G')], default=0),
        ),
        migrations.AlterField(
            model_name='phonelapmodel',
            name='memory_stick_lv',
            field=models.IntegerField(choices=[(0, '< 64G'), (1, '64-128G'), (2, '> 128G')], default=0),
        ),
        migrations.AlterField(
            model_name='phonelapmodel',
            name='os',
            field=models.IntegerField(choices=[(0, 'ios'), (1, 'android')]),
        ),
        migrations.AlterField(
            model_name='phonelapmodel',
            name='type_product',
            field=models.IntegerField(choices=[(0, 'Phone'), (1, 'Laptop')]),
        ),
    ]
